apiVersion: kyverno.io/v1
kind: ClusterPolicy
metadata:
  name: clone-secret
spec:
  rules:
  - name: clone-secret
    match:
      resources:
        kinds:
        - Namespace
    generate:
      kind: Secret
      name: dockerhub 
      namespace: "{{request.object.metadata.name}}"
      synchronize : true
      clone:
        namespace: default
        name: dockerhub
